In [1]:
import pandas as pd
food = pd.read_csv("en.openfoodfacts.org.products.csv", sep= "\t", on_bad_lines= "skip") # load the csv file in while accounting for unique tab separation amd skipping corrupt lines

/var/folders/dh/wndstd9948b8myqxw6g0hlfh0000gn/T/ipykernel_5618/3950525275.py:2: DtypeWarning: Columns (0: code, 1: abbreviated_product_name, 2: packaging, 3: packaging_tags, 4: packaging_en, 5: packaging_text, 6: origins, 7: origins_tags, 8: origins_en, 9: manufacturing_places, 10: manufacturing_places_tags, 11: emb_codes, 12: emb_codes_tags, 13: first_packaging_code_geo, 14: cities, 15: cities_tags, 16: purchase_places, 17: stores, 18: allergens_en, 19: traces, 20: serving_quantity, 21: no_nutrition_data, 22: additives_n, 23: additives, 24: nutriscore_score, 25: brand_owner, 26: owner) have mixed types. Specify dtype option on import or set low_memory=False.
  food = pd.read_csv("en.openfoodfacts.org.products.csv", sep= "\t", on_bad_lines= "skip") # load the csv file in while accounting for unique tab separation amd skipping corrupt lines

In [2]:
food.head() # check to see if DataFrame was correctly created

,code,url,creator,created_t,created_datetime,last_modified_t,last_modified_datetime,last_modified_by,last_updated_t,last_updated_datetime,...,choline_100g,phylloquinone_100g,beta-glucan_100g,inositol_100g,carnitine_100g,sulphate_100g,nitrate_100g,acidity_100g,carbohydrates-total_100g,water_100g
0,54,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1582569031,2020-02-24T18:30:31Z,1733085204,2024-12-01T20:33:24Z,NaN,1.740205e+09,2025-02-22T06:23:42Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,63,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1673620307,2023-01-13T14:31:47Z,1750061386,2025-06-16T08:09:46Z,bodysupport,1.750061e+09,2025-06-16T08:09:46Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,114,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1580066482,2020-01-26T19:21:22Z,1751035658,2025-06-27T14:47:38Z,teolemon,1.751036e+09,2025-06-27T14:47:38Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,431,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1714301712,2024-04-28T10:55:12Z,1714301721,2024-04-28T10:55:21Z,kiliweb,1.714302e+09,2024-04-28T10:55:21Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,105,http://world-en.openfoodfacts.org/product/0000...,kiliweb,1572117743,2019-10-26T19:22:23Z,1738073570,2025-01-28T14:12:50Z,NaN,1.743653e+09,2025-04-03T04:11:36Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
food.dtypes # check which types of data is present and if anything must be converted

code                         object
url                             str
creator                         str
created_t                     int64
created_datetime                str
                             ...
sulphate_100g               float64
nitrate_100g                float64
acidity_100g                float64
carbohydrates-total_100g    float64
water_100g                  float64
Length: 211, dtype: object

In [4]:
product_category = food[["product_name", "brands", "brands_tags"]] # create a subset with only the relevant columns for brand name extraction

In [5]:
product_category.head() # check to make sure subset was correctly created

                           product_name          brands        brands_tags
0         Limonade artisanale a la rose             NaN                NaN
1                         M&amp;M white        Fitpiggy        xx:fitpiggy
2                          Chocolate n3  Jeff de Bruges  xx:jeff-de-bruges
3                        Pâte de fruits             NaN                NaN
4  Paleta gran reserva - Sierra nevada-        AdvoCare        xx:advocare

In [6]:
complete_products = product_category.dropna(subset= "product_name") # drop missing product rows as they provide no value to our purpose of extracting brand names from product titles

In [7]:
complete_products.head() # check to make sure no "NaNs" are present

                           product_name          brands        brands_tags
0         Limonade artisanale a la rose             NaN                NaN
1                         M&amp;M white        Fitpiggy        xx:fitpiggy
2                          Chocolate n3  Jeff de Bruges  xx:jeff-de-bruges
3                        Pâte de fruits             NaN                NaN
4  Paleta gran reserva - Sierra nevada-        AdvoCare        xx:advocare

In [8]:
complete_products.count() # check to find missing data

product_name    4196933
brands          2774494
brands_tags     2774973
dtype: int64

In [9]:
lower_complete_products = complete_products
lower_complete_products["product_name"] = complete_products["product_name"].str.lower() # standardize all product names to lower case to help with brand name extraction through case insensitivity

In [10]:
lower_complete_products.head() # check to make sure lower casing was successful

                           product_name          brands        brands_tags
0         limonade artisanale a la rose             NaN                NaN
1                         m&amp;m white        Fitpiggy        xx:fitpiggy
2                          chocolate n3  Jeff de Bruges  xx:jeff-de-bruges
3                        pâte de fruits             NaN                NaN
4  paleta gran reserva - sierra nevada-        AdvoCare        xx:advocare

In [11]:
dupes = lower_complete_products[lower_complete_products.duplicated()] # check to see if there are duplicated rows
dupes

              product_name brands brands_tags
352      nutritional yeast    NaN         NaN
495        chips de banane    NaN         NaN
517      nutritional yeast    NaN         NaN
543                 erbsen    NaN         NaN
653      nutritional yeast    NaN         NaN
...                    ...    ...         ...
4532723       skimmed milk  Tesco    xx:tesco
4532744      جاري التحميل…    NaN         NaN
4532746     steak haché 5%    NaN         NaN
4532751     marrons glacés    NaN         NaN
4532753           chocolat    NaN         NaN

[839265 rows x 3 columns]

In [12]:
lower_complete_products = lower_complete_products.drop_duplicates() # drop all duplicated rows

In [13]:
brands_known = lower_complete_products.dropna(subset= ["brands"]) # we need the brand field present to establish ground truth, so drop empty brand field rows
brands_known = brands_known.dropna(subset= "product_name") # redundant, just in case

In [14]:
brands_known.head() # quick check to make sure no missing brand rows present, at least in a small sample

                            product_name          brands        brands_tags
1                          m&amp;m white        Fitpiggy        xx:fitpiggy
2                           chocolate n3  Jeff de Bruges  xx:jeff-de-bruges
4   paleta gran reserva - sierra nevada-        AdvoCare        xx:advocare
12              granola bio le chocolaté     Mg ricarica     xx:mg-ricarica
14                     xytitol pastilles    xylimgxyling    xx:xylimgxyling

In [15]:
print(brands_known['brands'].apply(type).value_counts()) # make sure all brand entries are strings
print(brands_known['product_name'].apply(type).value_counts()) # make sure all product name entries are strings

brands
<class 'str'>    2466907
Name: count, dtype: int64
product_name
<class 'str'>    2466907
Name: count, dtype: int64

In [16]:
brands_known["brands"] = brands_known["brands"].str.lower() # cleaning in order to account for edge cases where brand names may have unusual capitalization
brands_known["brands"] = brands_known["brands"].str.strip() # removing any white spaces at beginning or end to ensure labeling is easy to read
brands_known["brands"] = brands_known["brands"].str.replace("  ", " ") # removing extra spacing in labels
has_ground_truth = [brand in product for product, brand in zip(brands_known['product_name'], brands_known['brands'])] # filtering out all products which do not have their brand names somewhere in their product name

In [17]:
brands_known_products = brands_known.drop_duplicates() # again, redundant deduplication just in case

In [18]:
print(len(brands_known_products)) # see how many rows are remaining

2436009

In [19]:
sample = brands_known_products.sample(n= 500, random_state= 10) # take a random sample of 500 rows/products

In [20]:
sample

,product_name,brands,brands_tags
4454178,strawberry shortbread trifle,coles,xx:coles
2524731,cheese & onion foccacia rolls,aldi,xx:aldi
1814487,pate de campagne breton au cidre artisanal igp,mère lalie,xx:mere-lalie
1225093,spiced plum chutney,tracklements,xx:tracklements
3043695,energy gel,sis,xx:sis
...,...,...,...
3623572,"jason's deli, simply pomegranate dressing, bot...",jason's deli,jason-s-deli
4061263,burguer meat pollo y pavo,aldelis,xx:aldelis
1381569,lomo bajo corte de ternera,lidl,xx:lidl
447132,caramels,free range snack co,free-range-snack-co
2504544,jaegermeister,jägermeister,xx:jagermeister